Adding reel to instagram submodule
medialab/ural pull request #148
Opened 2023-03-01 16:17 UTC by MiguelLaura

2023-03-01 16:56 UTC, Yomguithereal commented
Que mijotes-tu @MiguelLaura? J'espère que tu as besoin de ça parce que tu collectes des trucs pour un projet perso et que tu n'es pas en train de travailler gratuitement :) ?

2023-03-01 18:24 UTC, MiguelLaura commented
J'en aurai potentiellement besoin pour un projet perso (et pour un cours). Je vais surtout avoir besoin de ce que je suis en train de rajouter sur minet :)

2023-03-01 19:17 UTC, Yomguithereal requested changes

2023-03-01 19:17 UTC, Yomguithereal commented on ural/instagram.py
> +INSTAGRAM_NOT_A_USER_LIST = ["accounts", "ads", "direct", "emails", "explore", "push", "reels", "session", "settings", "stories", "your_activity"]
Ceci devrait être un set je pense à ce stade.

2023-03-01 19:17 UTC, Yomguithereal commented on ural/instagram.py
> +    return bool(re.search(INSTAGRAM_POST_SHORTCODE_RE, value)) and value != "videos"
Conceptuellement ce `and` n'a pas sa place dans cette fonction. `videos` **est** un shortcode de post valide. Le fait de vérifier si c'est `videos` n'a de sens que quand on considère un path d'url, donc dans la fonction de parse, à mon sens. Tu ne trouves pas?

2023-03-01 19:17 UTC, Yomguithereal commented on ural/instagram.py
> +    return bool(re.search(INSTAGRAM_USERNAME_RE, value)) and value not in INSTAGRAM_NOT_A_USER_LIST
Idem

2023-03-01 19:17 UTC, Yomguithereal commented on ural/instagram.pyi
> +class InstagramReel(NameError):
`InstagramReel` devrait subclasser `NamedTuple`. Tu as succombé au copier-coller de ma bêtise avec `InstagramPost` (que je veux bien que tu corriges au passage du coup :) ).

2023-03-02 10:45 UTC, MiguelLaura commented on ural/instagram.py
> +    return bool(re.search(INSTAGRAM_USERNAME_RE, value)) and value not in INSTAGRAM_NOT_A_USER_LIST
Pour `videos` je suis d'accord, mais moins pour les username. Je suis sûre qu'aucun utilisateur ne peut porter ces noms (il n'y en a aucun actuellement, et si j'essaye de changer mon nom d'utilisateur pour un des ces mots instagram me dit que le nom est déjà pris), donc je dirai qu'ils ne sont pas valides même s'ils ont le bon format. Aussi j'utilise directement cette fonction dans minet pour vérifier qu'on me donne un username valide en entrée donc c'est plus partique si ces cas-là sont directement traités dans `is_instagram_username`

2023-03-02 10:53 UTC, Yomguithereal commented on ural/instagram.py
> +    return bool(re.search(INSTAGRAM_USERNAME_RE, value)) and value not in INSTAGRAM_NOT_A_USER_LIST
Fair enough

2023-03-02 12:53 UTC, merged

2023-03-02 12:57 UTC, Yomguithereal commented
`v0.39.0` live on pypi. Fais gaffe `minet` bouge beaucoup en ce moment.